// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaGestion.Models;

namespace SistemaGestion.Migrations
{
    [DbContext(typeof(DbConnection))]
    partial class DbConnectionModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaGestion.Models.CategoriaPcModelo", b =>
                {
                    b.Property<int>("CategoriaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoriaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoriaID");

                    b.ToTable("tblCategoriaPc");
                });

            modelBuilder.Entity("SistemaGestion.Models.ClientesModelo", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClienteApellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteCorreo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienteTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoID")
                        .HasColumnType("int");

                    b.HasKey("ClienteID");

                    b.HasIndex("TipoID");

                    b.ToTable("tblCliente");
                });

            modelBuilder.Entity("SistemaGestion.Models.ComputadorModelo", b =>
                {
                    b.Property<int>("ComputadorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<int>("ModeloID")
                        .HasColumnType("int");

                    b.Property<string>("PcDisco1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcDisco2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcProcesador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcRam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PcVideo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SistemaID")
                        .HasColumnType("int");

                    b.HasKey("ComputadorID");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("ModeloID");

                    b.HasIndex("SistemaID");

                    b.ToTable("tblComputador");
                });

            modelBuilder.Entity("SistemaGestion.Models.DetalleMantencionesModelo", b =>
                {
                    b.Property<int>("DetalleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ComputadorID")
                        .HasColumnType("int");

                    b.Property<int>("MantencionID")
                        .HasColumnType("int");

                    b.HasKey("DetalleID");

                    b.HasIndex("ComputadorID");

                    b.HasIndex("MantencionID");

                    b.ToTable("tblDetalleMantencion");
                });

            modelBuilder.Entity("SistemaGestion.Models.EstadoMantencionModelo", b =>
                {
                    b.Property<int>("EstadoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstadoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoID");

                    b.ToTable("tblEstadoMantencion");
                });

            modelBuilder.Entity("SistemaGestion.Models.MantencionesModelo", b =>
                {
                    b.Property<int>("MantencionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<string>("MantencionFallas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MantencionFecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MantencionImpuesto")
                        .HasColumnType("int");

                    b.Property<int>("MantencionPrecio")
                        .HasColumnType("int");

                    b.Property<string>("MantencionProceso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MantencionTotal")
                        .HasColumnType("int");

                    b.Property<int>("MetodoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("MantencionID");

                    b.HasIndex("ClienteID");

                    b.HasIndex("EstadoID");

                    b.HasIndex("MetodoID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("tblMantencion");
                });

            modelBuilder.Entity("SistemaGestion.Models.MarcaPcModelo", b =>
                {
                    b.Property<int>("MarcaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MarcaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaID");

                    b.ToTable("tblMarca");
                });

            modelBuilder.Entity("SistemaGestion.Models.MetodoPagoModelo", b =>
                {
                    b.Property<int>("MetodoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MetodoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MetodoID");

                    b.ToTable("tblMetodoPago");
                });

            modelBuilder.Entity("SistemaGestion.Models.ModelosPcModelo", b =>
                {
                    b.Property<int>("ModeloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MarcaID")
                        .HasColumnType("int");

                    b.Property<string>("ModeloNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModeloID");

                    b.HasIndex("MarcaID");

                    b.ToTable("tblModelo");
                });

            modelBuilder.Entity("SistemaGestion.Models.ProveedorSIstemaModelo", b =>
                {
                    b.Property<int>("ProveedorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProveedorNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProveedorID");

                    b.ToTable("tblProveedorSistema");
                });

            modelBuilder.Entity("SistemaGestion.Models.RolModelo", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RolNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("tblRolUsuario");
                });

            modelBuilder.Entity("SistemaGestion.Models.SistemaOperativoModelo", b =>
                {
                    b.Property<int>("SistemaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProveedorID")
                        .HasColumnType("int");

                    b.Property<string>("SistemaNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SistemaID");

                    b.HasIndex("ProveedorID");

                    b.ToTable("tblSistemaOperativo");
                });

            modelBuilder.Entity("SistemaGestion.Models.TipoCModelo", b =>
                {
                    b.Property<int>("TipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoID");

                    b.ToTable("tblTipoCliente");
                });

            modelBuilder.Entity("SistemaGestion.Models.UsuarioModelo", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAlias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioPass")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("RolID");

                    b.ToTable("tblUsuario");
                });

            modelBuilder.Entity("SistemaGestion.Models.ClientesModelo", b =>
                {
                    b.HasOne("SistemaGestion.Models.TipoCModelo", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("SistemaGestion.Models.ComputadorModelo", b =>
                {
                    b.HasOne("SistemaGestion.Models.CategoriaPcModelo", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestion.Models.ModelosPcModelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestion.Models.SistemaOperativoModelo", "Sistema")
                        .WithMany()
                        .HasForeignKey("SistemaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Modelo");

                    b.Navigation("Sistema");
                });

            modelBuilder.Entity("SistemaGestion.Models.DetalleMantencionesModelo", b =>
                {
                    b.HasOne("SistemaGestion.Models.ComputadorModelo", "Computador")
                        .WithMany()
                        .HasForeignKey("ComputadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestion.Models.MantencionesModelo", "Mantencion")
                        .WithMany()
                        .HasForeignKey("MantencionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Computador");

                    b.Navigation("Mantencion");
                });

            modelBuilder.Entity("SistemaGestion.Models.MantencionesModelo", b =>
                {
                    b.HasOne("SistemaGestion.Models.ClientesModelo", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestion.Models.EstadoMantencionModelo", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestion.Models.MetodoPagoModelo", "Metodo")
                        .WithMany()
                        .HasForeignKey("MetodoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaGestion.Models.UsuarioModelo", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Estado");

                    b.Navigation("Metodo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaGestion.Models.ModelosPcModelo", b =>
                {
                    b.HasOne("SistemaGestion.Models.MarcaPcModelo", "Marca")
                        .WithMany()
                        .HasForeignKey("MarcaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("SistemaGestion.Models.SistemaOperativoModelo", b =>
                {
                    b.HasOne("SistemaGestion.Models.ProveedorSIstemaModelo", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("SistemaGestion.Models.UsuarioModelo", b =>
                {
                    b.HasOne("SistemaGestion.Models.RolModelo", "Rol")
                        .WithMany()
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
